apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: distributed-ecommerce
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:daniloitagyba/SagaEcommerce.git
    targetRevision: main
    path: kubernetes/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: orders-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Rollout
      name: orders-api
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: Deployment
      name: orders-worker
      jsonPointers:
        - /spec/replicas
