apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: partition-orders-api-from-postgres
  namespace: orders-lab
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - orders-lab
    labelSelectors:
      app.kubernetes.io/name: orders-api
  direction: both
  externalTargets:
    - "172.30.0.10"
  duration: "45s"
