apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-orders-worker
  namespace: orders-lab
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - orders-lab
    labelSelectors:
      app.kubernetes.io/name: orders-worker
