apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: skew-orders-worker-clock
  namespace: orders-lab
spec:
  mode: one
  selector:
    namespaces:
      - orders-lab
    labelSelectors:
      app.kubernetes.io/name: orders-worker
  timeOffset: "180s"
  clockIds:
    - CLOCK_REALTIME
  containerNames:
    - orders-worker
  duration: "60s"
