apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: orders-ha
  namespace: postgres-ha
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4
  storage:
    size: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  bootstrap:
    initdb:
      database: orders_ha_demo
      owner: orders_ha_demo
  backup:
    barmanObjectStore:
      destinationPath: s3://postgres-backups/orders-ha
      endpointURL: http://minio.orders-lab.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: minio-backup-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-backup-credentials
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
  postgresql:
    parameters:
      max_connections: "50"
