apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders-api
  labels:
    app.kubernetes.io/name: orders-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-service
  labels:
    app.kubernetes.io/name: payments-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-service
  labels:
    app.kubernetes.io/name: catalog-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-service
  labels:
    app.kubernetes.io/name: inventory-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cart-service
  labels:
    app.kubernetes.io/name: cart-service
