apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orders-lab
resources:
  - namespace.yaml
  - infrastructure-services.yaml
  - orders-runtime-sealed-secret.yaml
  - orders-api.yaml
  - orders-api-hpa.yaml
  - orders-api-analysis-template.yaml
  - orders-worker.yaml
  - orders-worker-serviceaccount.yaml
  - orders-worker-scaledobject.yaml
  - migration-job.yaml
  - payments-service.yaml
  - payments-migration-job.yaml
  - catalog-service.yaml
  - catalog-seed-job.yaml
  - inventory-service.yaml
  - inventory-migration-job.yaml
  - inventory-seed-job.yaml
  - cart-service.yaml
  - storefront-service.yaml
  - storefront-service-serviceaccount.yaml
  - network-policies.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: saga-ecommerce
      app.kubernetes.io/managed-by: kustomize
