apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../local
images:
  - name: saga-ecommerce/orders-api
    newName: ghcr.io/daniloitagyba/saga-ecommerce/orders-api
    digest: sha256:0939d86a2c5f18be3e02ea642036efc71a2494f0e1f215b5da238f64b9cc036b
  - name: saga-ecommerce/orders-worker
    newName: ghcr.io/daniloitagyba/saga-ecommerce/orders-worker
    digest: sha256:844290c4b3a00c0fd4a98aea8480583a2f916c4a0e3be775bb1eeb59e36de5ba
  - name: saga-ecommerce/payments-service
    newName: ghcr.io/daniloitagyba/saga-ecommerce/payments-service
    digest: sha256:8886cb31b3db43d7ba5dcc3af4a09d0f5a81c6d9111e28ec91e5063d75e0c5b5
  - name: saga-ecommerce/catalog-service
    newName: ghcr.io/daniloitagyba/saga-ecommerce/catalog-service
    digest: sha256:9eb54a19513e8c0cb6a9b33a93c235ca2defb7e5698d410bbdc6035dccbeedf8
  - name: saga-ecommerce/inventory-service
    newName: ghcr.io/daniloitagyba/saga-ecommerce/inventory-service
    digest: sha256:7f09889157c87e13fed07bfbbeb4e6eb9a21e9d820d822a23e3e57e3f29dabbc
  - name: saga-ecommerce/cart-service
    newName: ghcr.io/daniloitagyba/saga-ecommerce/cart-service
    digest: sha256:ba58f8b05c1f1de2f793dc2abf4ea45d09f8d598b65f002c71f65e1c36dd4fc4
  - name: saga-ecommerce/storefront-service
    newName: ghcr.io/daniloitagyba/saga-ecommerce/storefront-service
    digest: sha256:9e3334e1716a46166b0a6b391fb480848c0dd1cc0fff20e1590153f8a9df7000
