apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orders-lab
resources:
  - ../../base
  - infrastructure-endpoints.yaml
  - connectivity-job.yaml
images:
  - name: saga-ecommerce/orders-api
    newTag: local
  - name: saga-ecommerce/orders-worker
    newTag: local
  - name: saga-ecommerce/payments-service
    newTag: local
  - name: saga-ecommerce/catalog-service
    newTag: local
  - name: saga-ecommerce/inventory-service
    newTag: local
  - name: saga-ecommerce/cart-service
    newTag: local
  - name: saga-ecommerce/storefront-service
    newTag: local
patches:
  - target:
      kind: Rollout
      name: orders-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: orders-worker
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: payments-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Job
      name: orders-migrations-m7
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Job
      name: payments-migrations-m12
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: catalog-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Job
      name: catalog-seed-m40
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: inventory-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Job
      name: inventory-migrations-m41
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Job
      name: inventory-seed-m41
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: cart-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: storefront-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
